const ENV = process.env;

const ADMIN_NAME = ENV.ADMIN_NAME || ENV.USER_NAME;
const PASSWORD = ENV.PASSWORD || ENV.USER_PASSWORD;

const DEVELOPMENT = ENV.DEVELOPMENT === 'true';

const MAILGUN_API_KEY = ENV.MAILGUN_API_KEY;
const MAILGUN_EMAIL = ENV.MAILGUN_EMAIL;

const PORT = ENV.PORT;

const REDIS_URL = ENV.REDIS_URL;

module.exports = {
  ADMIN_NAME,
  PASSWORD,
  DEVELOPMENT,
  MAILGUN_API_KEY,
  MAILGUN_EMAIL,
  PORT,
  REDIS_URL
};
