const AIRPORTS = {
  'ABQ': 'Albuquerque, NM',
  'ALB': 'Albany, NY',
  'AMA': 'Amarillo, TX',
  'ATL': 'Atlanta, GA',
  'AUA': 'Aruba, Aruba',
  'AUS': 'Austin, TX',
  'BDL': 'Hartford, CT',
  'BHM': 'Birmingham, AL',
  'BNA': 'Nashville, TN',
  'BOI': 'Boise, ID',
  'BOS': 'Boston Logan, MA',
  'BUF': 'Buffalo/Niagara, NY',
  'BUR': 'Burbank, CA',
  'BWI': 'Baltimore/Washington, MD',
  'BZE': 'Belize City, Belize',
  'CHS': 'Charleston, SC',
  'CLE': 'Cleveland, OH',
  'CLT': 'Charlotte, NC',
  'CMH': 'Columbus, OH',
  'CRP': 'Corpus Christi, TX',
  'CUN': 'Cancun, Mexico',
  'CVG': 'Cincinnati, OH',
  'DAL': 'Dallas (Love Field), TX',
  'DCA': 'Washington (Reagan National), DC',
  'DEN': 'Denver, CO',
  'DSM': 'Des Moines, IA',
  'DTW': 'Detroit, MI',
  'ECP': 'Panama City Beach, FL',
  'ELP': 'El Paso, TX',
  'EWR': 'New York/Newark, NJ',
  'FLL': 'Ft. Lauderdale, FL',
  'FNT': 'Flint, MI',
  'GCM': 'Grand Cayman, Cayman Islands',
  'GEG': 'Spokane, WA',
  'GRR': 'Grand Rapids, MI',
  'GSP': 'Greenville/Spartanburg, SC',
  'HAV': 'Havana, Cuba',
  'HOU': 'Houston (Hobby), TX',
  'HRL': 'Harlingen, TX',
  'IAD': 'Washington (Dulles), DC',
  'ICT': 'Wichita, KS',
  'IND': 'Indianapolis, IN',
  'ISP': 'Long Island/Islip, NY',
  'JAX': 'Jacksonville, FL',
  'LAS': 'Las Vegas, NV',
  'LAX': 'Los Angeles, CA',
  'LBB': 'Lubbock, TX',
  'LGA': 'New York (LaGuardia), NY',
  'LGB': 'Long Beach, CA',
  'LIR': 'Liberia, Costa Rica',
  'LIT': 'Little Rock, AR',
  'MAF': 'Midland/Odessa, TX',
  'MBJ': 'Montego Bay, Jamaica',
  'MCI': 'Kansas City, MO',
  'MCO': 'Orlando, FL',
  'MDW': 'Chicago (Midway), IL',
  'MEM': 'Memphis, TN',
  'MEX': 'Mexico City, Mexico',
  'MHT': 'Manchester, NH',
  'MKE': 'Milwaukee, WI',
  'MSP': 'Minneapolis/St. Paul (Terminal 2), MN',
  'MSY': 'New Orleans, LA',
  'NAS': 'Nassau, Bahamas',
  'OAK': 'Oakland, CA',
  'OKC': 'Oklahoma City, OK',
  'OMA': 'Omaha, NE',
  'ONT': 'Ontario/LA, CA',
  'ORF': 'Norfolk, VA',
  'PBI': 'West Palm Beach, FL',
  'PDX': 'Portland, OR',
  'PHL': 'Philadelphia, PA',
  'PHX': 'Phoenix, AZ',
  'PIT': 'Pittsburgh, PA',
  'PLS': 'Providenciales, Turks and Caicos',
  'PNS': 'Pensacola, FL',
  'PUJ': 'Punta Cana, DO',
  'PVD': 'Providence, RI',
  'PVR': 'Puerto Vallarta, MX',
  'PWM': 'Portland, ME',
  'RDU': 'Raleigh/Durham, NC',
  'RIC': 'Richmond, VA',
  'RNO': 'Reno/Tahoe, NV',
  'ROC': 'Rochester, NY',
  'RSW': 'Ft. Myers, FL',
  'SAN': 'San Diego, CA',
  'SAT': 'San Antonio, TX',
  'SDF': 'Louisville, KY',
  'SEA': 'Seattle/Tacoma, WA',
  'SFO': 'San Francisco, CA',
  'SJC': 'San Jose, CA',
  'SJD': 'Cabo San Lucas/Los Cabos, MX',
  'SJO': 'San Jose, Costa Rica',
  'SJU': 'San Juan, PR',
  'SLC': 'Salt Lake City, UT',
  'SMF': 'Sacramento, CA',
  'SNA': 'Orange County/Santa Ana, CA',
  'STL': 'St. Louis, MO',
  'TPA': 'Tampa, FL',
  'TUL': 'Tulsa, OK',
  'TUS': 'Tucson, AZ'
};

module.exports = {
  codeIsValid: function (code) {
    return (AIRPORTS.code === undefined);
  },

  getAirportName: function (code) {
    return AIRPORTS.code;
  }
};
